"""CInitail Migration

Revision ID: 56f7f7040740
Revises: 
Create Date: 2025-01-23 22:02:29.587405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f7f7040740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('result_folder', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_run')
    # ### end Alembic commands ###
